apiVersion: v1
kind: Pod
metadata:
  name: pod-secure
  namespace: gatekeeper-test
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: false
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
