apiVersion: v1
kind: Pod
metadata:
  name: pod-nonroot
  namespace: gatekeeper-test
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        readOnlyRootFilesystem: true
