apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PrivilegedPods
metadata:
  name: privileged-pods
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "gatekeeper-test"
