apiVersion: v1
kind: Pod
metadata:
  name: pod-no-hostpath
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
  volumes:
    - name: empty-dir
      emptyDir: {}